name: Run ServiceNow ATF

on:
  push:
    branches:
      - main

jobs:
  run-atf-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Trigger ServiceNow ATF Test Suite1
        run: |
          curl -X POST https://dev400373.service-now.com/api/sn_cicd/testsuite/run?test_suite_sys_id=106f5a35c32776505e811c84e401311c \
          -u admin_santosh:S1ttu@12 \
          -H "Content-Type: application/json"

