name: Run ServiceNow ATF

on:
  push:
    branches:
      - main

jobs:
  run-atf-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Trigger ServiceNow ATF Test Suite
        run: |
          curl -X POST https://${{ secrets.SN_INSTANCE }}/api/sn_atf/testsuite/run \
          -u ${{ secrets.SN_USERNAME }}:${{ secrets.SN_PASSWORD }} \
          -H "Content-Type: application/json" \
          -d '{
                "test_suite_sys_id": "${{ secrets.SN_TEST_SUITE }}"
              }'
